name: Fetch and Predict Penguin

on:
  schedule:
    - cron: "30 6 * * *"  # Hver dag kl. 07:30 CET (6:30 UTC)
  workflow_dispatch:       # Mulighed for at køre manuelt

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Debug - List root directory
      run: ls -la

    - name: Install dependencies
      run: pip install -r ./requirements.txt

    - name: Run prediction script
      run: python predict.py  # Sørg for at du har en 'predict.py'-fil i roden

    - name: Commit and push prediction
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add prediction.txt
        git commit -m "Opdateret prediction"
        git push
