name: Fetch and Predict Penguin

on:
  schedule:
    - cron: "30 6 * * *"  # Hver dag kl. 07:30 dansk tid (CET)
  workflow_dispatch:

jobs:
  predict:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies (fallback)
      run: |
        pip install numpy pandas requests scikit-learn joblib

    - name: Run prediction script
      run: python predict.py

    - name: Commit and push prediction
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add prediction.txt
        git commit -m "Opdateret prediction"
        git push
